name: Android CI

on:
  push:
    branches: [ "main","Testing" ]
  pull_request:
    branches: [ "main","Testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK artifacts
      run: |
        for apk in $(find . -type f -name "*.apk"); do
          echo "Uploading $apk"
          actions/upload-artifact $apk
        done
